# This workflow will create a GitHub release every time a tag is pushed
name: Create GitHub Release

on:
  push:
    tags:
      - "v2.*"
      - "v3.*"

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        # ,  See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npx playwright install-deps
      - run: npm ci
      - run: npm run vbuild
      - uses: actions/upload-artifact@master
        with:
          name: buildfiles
          path: $GITHUB_WORKSPACE/dist

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Fetch build
        uses: actions/download-artifact@master
        with:
          name: buildfiles
          path: $GITHUB_WORKSPACE/dist

      - name: archive
        run: cd $GITHUB_WORKSPACE/dist && zip shoelace.zip -r ./*

      - name: create release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false,
          files: |
            $GITHUB_WORKSPACE/dist/shoelace.zip
